# Generated by Django 4.1.4 on 2022-12-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_id', models.CharField(max_length=200)),
                ('date_create', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Корзина',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('image_one', models.ImageField(upload_to='static/product/')),
                ('image_two', models.ImageField(upload_to='static/product/')),
                ('image_three', models.ImageField(upload_to='static/product/')),
                ('image_four', models.ImageField(upload_to='static/product/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amado.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_session_id', models.CharField(max_length=200, verbose_name='ИД сессии гостя')),
                ('fname', models.CharField(max_length=200, verbose_name='Имя')),
                ('lname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('mail', models.CharField(max_length=200, verbose_name='Почта')),
                ('date_create', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('zip', models.CharField(max_length=200, null=True, verbose_name='Почтовый индекс')),
                ('comment', models.CharField(max_length=400, null=True, verbose_name='Комментарий')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=20, null=True, verbose_name='Итоговая сумма')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amado.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amado.orders', verbose_name='ИД заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amado.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Элемент деталей заказа',
                'verbose_name_plural': 'Детали заказов',
            },
        ),
        migrations.CreateModel(
            name='CartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amado.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amado.product')),
            ],
            options={
                'verbose_name': 'Элемент деталей корзины',
                'verbose_name_plural': 'Детали корзины',
            },
        ),
    ]
